image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build --build-arg APP_NAME="${APP_NAME}" --build-arg PRIVATE_KEY="${PRIVATE_KEY}" --file Dockerfile --tag $IMAGE_NAME .
            - docker save $IMAGE_NAME --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker tag "${IMAGE_NAME}" "antoniomoscato/gestionale:${VERSION}"
            - docker push "antoniomoscato/gestionale:${VERSION}"
          services:
            - docker
